create cf-diego metadata script fails if it does not find diego version [#99724170]
Signed-off-by: Morgan Fine <mfine@pivotal.io>

diff --git a/ci/scripts/create-cf-diego-salmon-metadata b/ci/scripts/create-cf-diego-salmon-metadata
--- a/ci/scripts/create-cf-diego-salmon-metadata
+++ b/ci/scripts/create-cf-diego-salmon-metadata
@@ -18,6 +18,11 @@ export DIEGO_VERSION=`curl https://github.com/cloudfoundry/cf-release/releases/t
   | sed -n 's/.*\([0-9]\.[0-9]\{4\}\.[0-9]\).*/\1/p' \
   | tr -d '\r\n'`
 
+if [ -z "$DIEGO_VERSION" ]; then
+  echo "Diego version not found in release notes"
+  exit 1
+fi
+
 export DIEGO_URL=https://bosh.io/releases/github.com/cloudfoundry-incubator/diego-release?version=$DIEGO_VERSION
 
 wget $DIEGO_URL -O diego-$DIEGO_VERSION.tgz
